## webapp

hostname: nerdtrack
webserver_name: spree.example.com
deploy_directory: /var/www/nerdtrack
app_name: nerdtrack

database:
    name: nerdtrack
    user: root
    passwd: root

ruby:
    version: 1.8.7-p375

rbenv_root: /usr/local/rbenv
rbenv_env: "RBENV_ROOT={{ rbenv_root }} PATH=/usr/local/bin:{{ rbenv_root }}/shims:{{ rbenv_root }}/bin:$PATH"
rbenv_bin: "{{ rbenv_env }} rbenv"
